manager:
  name: forest-server
  domain: forest.informaticslab.co.uk
  port: 8888
  revision: "HEAD"

managerdev:
  name: forest-server-dev
  domain: forestkube.informaticslab.co.uk
  port: 8888
  revision: "d280b756cbf2df31c3218ccbbe6d2d7af2693c05"
