Parameters:

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to an instance
    Type: AWS::EC2::KeyPair::KeyName

  ServiceOwner:
    Description: The owner of the service which costs are attributed to
    Type: String

  ServiceCode:
    Description: The code attached to the service which costs are attributed to
    Type: String

  ServiceName:
    Description: The name of the service which costs are attributed to
    Type: String

  ProjectName:
    Description: The name of the project
    Default: forest
    Type: String
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: Name must be in lower case or numeric

  ArtifactS3Bucket:
    Description: Bucket used by CodePipeline to store code
    Type: String

  ArtifactS3Key:
    Description: Object key used by CodePipeline to store code
    Type: String

  UniqueEnvName:
    Type: String
    Default: prototype
    Description: Unique environment name

  CollaborationBucketName:
    Type: String
    Default: met-office-rmed-collab-stack
    Description: Collaboration bucket name


Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref CollaborationBucketName
      Tags:
        - Key: ServiceOwner
          Value: !Ref ServiceOwner
        - Key: ServiceCode
          Value: !Ref ServiceCode
        - Key: ServiceName
          Value: !Ref ServiceName

  HelloWorldLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda:*"

  HelloWorldLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda"
      Handler: stack/src/presign.handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt HelloWorldLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Sub "${ArtifactS3Bucket}"
        S3Key: !Sub "${ArtifactS3Key}"
      Environment:
        Variables:
          BUCKET: !Ref CollaborationBucketName
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda"
        - Key: ServiceOwner
          Value: !Ref ServiceOwner
        - Key: ServiceCode
          Value: !Ref ServiceCode
        - Key: ServiceName
          Value: !Ref ServiceName

  HelloWorldLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt HelloWorldLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*"

  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectName}-${UniqueEnvName}-${AWS::Region}-api-gateway"
      Description: Pre-signed URL API
      # The Body is the OPEN API (Swagger) Standard.
      # http://editor.swagger.io/
      Body:
        components:
          schemas:
            PresignSchema:
              body:
                type: string
        info:
          description: Simple pre-signed URL API with Lambda integration
          title: Pre-signed URL API
          version: 0.1.0
        openapi: 3.0.0
        paths:
          /presign/{file_name}:
            get:
              description: Generate pre-signed S3 URL
              parameters:
                - name: file_name
                  in: path
                  required: true
                  schema:
                    type: string
              responses:
                '200':
                  description: Successful generation of URL
                  content:
                    application/json:
                      schema:
                        $ref: "#components/schemas/PresignSchema"
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
              x-amazon-apigateway-integration:
                httpMethod: POST
                responses:
                  default:
                    requestParameters:
                      integration.request.path.file_name: method.request.querystring.file_name
                    requestTemplates:
                      application/json: $input.json('$')
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'GET'"
                      method.response.header.Access-Control-Allow-Origin: "'*'" # This should be locked down to requesting domains unless it's a public API.
                    responseTemplates:
                      application/json: $input.json('$')
                    statusCode: 200
                type: aws
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}-${UniqueEnvName}-${AWS::Region}-lambda/invocations"


  # The API Gateway Deployment after the gateway is done.
  # NOTE: A manual re-deploy is needed to get REST API changes
  APIGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [HelloWorldLambdaPermission]
    Properties:
      RestApiId: !Ref APIGateway
      StageDescription:
        #### Uncomment to enable caching ###
        # CacheClusterEnabled: true
        # CacheClusterSize: '0.5'
        # CacheTtlInSeconds: 60
        # CachingEnabled: true
        MetricsEnabled: true
        Tags:
          - Key: Environment
            Value: !Ref UniqueEnvName
          - Key: ServiceCode
            Value: !Ref ServiceCode
          - Key: ServiceName
            Value: !Ref ServiceName
          - Key: ServiceOwner
            Value: !Ref ServiceOwner
      StageName: v1
