# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.manager.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.manager.name }}
    spec:
      containers:
        - image: informaticslab/singleuser-notebook:0.3.0
          command: ["bash"]
          args: ["-c",". /github_repos/forest/forest_lib/run_forest_server.sh /s3 {{ .Values.manager.port}} /github_repos/forest/bokeh_apps/"]
#          command: ["python"]
#          args: ["-c","import time; time.sleep(5000)"]

          name: {{ .Values.manager.name }}
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
          env:

            - name: PYTHONPATH
              value: /github_repos/forest/forest_lib/

          volumeMounts:
            - mountPath: /github_repos/
              name: git-volume

#            - mountPath: /s3
#              name: pysssix

            - name: goofys-forest
              mountPath: /s3/stephen-sea-public-london/

      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/informatics-lab/forest.git"
            revision: "f2f5f722c055be634973b8147917faca5518d59d"


#        - name: pysssix
#          flexVolume:
#            driver: "informaticslab/pysssix-flex-volume"



        - name: goofys-forest
          flexVolume:
            driver: "informaticslab/goofys-flex-volume"
            options:
              # Required
              bucket: "stephen-sea-public-london"