# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.manager.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.manager.name }}
    spec:
      containers:
        - image: informaticslab/singleuser-notebook:0.3.0
          command: ["bokeh"]
          args: ["serve","--port=8888","/forest_repo/bokeh_apps/*"]
          name: {{ .Values.manager.name }}
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
          env:

            - name: PYTHONPATH
              value: /forest_repo/forest/

          volumeMounts:
            - mountPath: /forest_repo
              name: git-volume

#          volumeMounts:
#            - name: goofys-stephen-sea-public-london
#              mountPath: /s3/stephen-sea-public-london

          volumeMounts:
            - mountPath: /s3
              name: pysssix


      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/informatics-lab/model_evaluation_tool.git"
            revision: "HEAD"


#        - name: goofys-stephen-sea-public-london
#          flexVolume:
#            driver: "informaticslab/goofys-fuse-flex-volume"
#            options:
#              # Required
#              bucket: "stephen-sea-public-london"

#      volumes:
        - name: pysssix
          flexVolume:
            driver: "informaticslab/pysssix-fuse-flex-volume"
            options:



---
# Service
kind: Service
metadata:
  name: {{ .Values.manager.name }}
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: {{ .Values.manager.name }}

---

# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.manager.domain }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.manager.domain }}
    secretName: {{ .Values.manager.domain }}-tls
  rules:
  - host: {{ .Values.manager.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.manager.name }}
          servicePort: 8888



